ItineraryItemSchema_AH_111824
Code-the-Dream-School/hh-team1-back pull request #10
Opened 2024-11-19 00:16 UTC by AmandaHockmuth

Created model folder and added Itinerary Item Schema, installed joi to handle "required" and "date."

2024-11-20 23:20 UTC, jgoldenberg29 requested changes
This schema is looking great! Love the error handling early on. Let's make the change to remove status. Other than that, it looks good to me.

2024-11-21 06:08 UTC, umavenki commented on models/ItineraryItem.js
> +      state: {
Should we add zip code?

2024-11-22 18:30 UTC, AmandaHockmuth commented on models/ItineraryItem.js
> +      state: {
Absolutely! Adding

2024-11-24 00:08 UTC, jgoldenberg29 approved these changes
Nicely done. Looks great!

2024-11-24 22:22 UTC, katsiarynalashcheuskaya approved these changes
Great work, Amanda!

2024-11-25 20:25 UTC, StuvaScript approved these changes

2024-12-04 22:00 UTC, merged