Routes edits by stu 12.16.24
Code-the-Dream-School/hh-team1-back pull request #29
Opened 2024-12-17 21:01 UTC by StuvaScript

2024-12-18 02:17 UTC, jgoldenberg29 approved these changes
Everything looks good to me Sisi! keep it up! Very nice error handling!

2024-12-18 02:30 UTC, jgoldenberg29 requested changes
looks good to me. The only thing I would change is the error message for incorrect password should say "invalid credentials" like the incorrect email one. We don't really want people to know which piece is incorrect. This might be the same on routes branch and I just missed it. Good work stu 👍

2024-12-18 02:30 UTC, jgoldenberg29 approved these changes

2024-12-29 00:44 UTC, Sisi-tech commented
> invalid credentials

I corrected the error message. thx

2025-01-01 23:20 UTC, Sisi-tech approved these changes

2025-01-01 23:21 UTC, merged