AmbiguousNamingCorrections_AH_12/18/24
Code-the-Dream-School/hh-team1-back pull request #31
Opened 2024-12-19 02:24 UTC by AmandaHockmuth

2024-12-20 16:51 UTC, jgoldenberg29 commented on src/controllers/ticketmasterController.js
> +  if (dateRangeStart && dateRangeStart !== "null") {
null is a falsy value so if dateRangeStart is truthy and this if statement does not short circuit before the '&&'  then dateRangeStart will never equal null, so we don't really need the second part of the conditional.

2024-12-20 16:51 UTC, jgoldenberg29 requested changes
It looks like there will be a conflict between this branch and your deployment update branch on the route for ticketmasterRouter. Just a heads up.

I also made one comment in the code on our date conditionals

2024-12-28 00:39 UTC, AmandaHockmuth commented
Newest commit addresses removal of `&& dateRangeEnd !== null` for both dates in controller.

2024-12-30 17:38 UTC, jgoldenberg29 approved these changes

2025-01-01 23:39 UTC, Sisi-tech approved these changes

2025-01-01 23:43 UTC, merged